http:
  port: 8080
  shutdownTimeout: 5s
  readHeaderTimeout: 1s

postgres:
  host: postgres
  port: 5432
  database: postgres
  username: postgres
  password: postgres

Logger:
  Enable: true
  # trace, debug, info (default), warn, error, fatal, panic, disabled
  Level: info
  # json (default), console
  Format: json
  # default 2006-01-02T15:04:05.999999999Z07:00
  TimeFormat: 2006-01-02T15:04:05.999999999Z07:00
  # false (default), true
  Caller: false
  OTLP:
    # http, grpc (default)
    Protocol: grpc
    # default localhost:4318
    Endpoint: localhost:4318
    Insecure: true

Tracer:
  Enable: true
  OTLP:
    # http, grpc (default)
    Protocol: grpc
    # default localhost:4318
    Endpoint: localhost:4318
    Insecure: true

Metric:
  # false (default), true
  Enable: true
  # Enable Prometheus collectors
  # false (default), true
  Prometheus: true
  # Metric interval
  # default 10s
  Interval: 10s
  OTLP:
    # http, grpc (default)
    Protocol: grpc
    # default localhost:4318
    Endpoint: localhost:4318
    Insecure: true
