---
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    jsonData:
      tracesToLogsV2:
        datasourceUid: "Loki"
        filterByTraceID: true
        filterBySpanID: true
      tracesToMetrics:
        datasourceUid: "Prometheus"
        filterByTraceID: true
        filterBySpanID: true
      nodeGraph:
        enabled: true
