---
name: Run Tests and Build

on:
  push:
    branches:
      - master

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install
        run: make install

      - name: Run tests
        run: make test

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: results/unit-tests.xml

      - name: Generate coverage report
        run: make coverage

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/system.out

      - name: Upload HTML Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: coverage/system.html

      - name: Build project
        run: make build
